[project]
authors = ["llango<rontomai@gmail.com>"]
channels = ["https://repo.prefix.dev/mojo-force", "conda-forge", "https://conda.modular.com/max"]
description = "a standard C library for Mojo programming language."
name = "libc"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.1"


[tasks]
test = "mojo run tests/test_main.mojo"
build = "rattler-build build -r src -c https://conda.modular.com/max -c conda-forge --skip-existing=all"
publish = { cmd = "bash scripts/publish.sh", env = { PREFIX_API_KEY = "$PREFIX_API_KEY" } }

[dependencies]
max = ">=24.5.0,<25"
python = ">=3.8,==3.12"